{
 "title": "demo-realtime-log-analytics",
 "description": "Connect to gdn.paas.macrometa.io",
 "time": { "from": "2020-12-19T14:14:00.000Z", "to": "2020-12-20T04:54:00.000Z" },
 "panels": [
  {
   "title": "HTTP GET Requsts",
   "type": "graph",
   "description": "Get counts of GET requests.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "queryText": "FOR doc IN http_verb_agg_counts  \nLIMIT 500\nRETURN {    \n time: doc.log.timestamp ,\n value : doc.log.GET\n}"
    }
   ]
  },
  {
   "title": "HTTP Code 200",
   "type": "graph",
   "description": "Get requests of code HTTP code 200.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "queryText": "FOR doc IN http_code_agg_counts  \nLIMIT 500\nRETURN {    \n time: doc.log.timestamp ,\n value : doc.log[\"200\"]\n}"
    }
   ]
  },
  {
   "title": "HTTP Code 400",
   "type": "graph",
   "description": "Display requests of HTTP error code 404.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Error 404" }
   ],
   "targets": [
    {
     "queryText": "FOR doc IN http_code_agg_counts  \nLIMIT 500\nRETURN {    \n time: (doc.log.timestamp) ,\n value : (doc.log[\"404\"]) \n}"
    }
   ]
  },
  {
   "title": "Table_Verb_GET",
   "type": "table",
   "description": "Get counts of GET requests.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "FOR doc IN http_verb_agg_counts  \nLIMIT 500\nRETURN {    \n time: (doc.log.timestamp) ,\n value : (doc.log.GET) \n}"
    }
   ]
  },
  {
   "title": "Verb_POST",
   "type": "timeseries",
   "description": "Get counts of POST requests.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "queryText": "FOR doc IN http_verb_agg_counts  \nLIMIT 500\nRETURN {    \n time: doc.log.timestamp ,\n value : doc.log.POST\n}"
    }
   ]
  }
 ]
}